### ISSUE TITLE
Icon invisible in dark mode

### ISSUE THREAD

**Issue by ploum** [shubhamjain/quick-grayscale#1]
Icon is dark and thus invisible in darkmode.

Thanks for the software, really helpful ;-)

**Comment by shubhamjain** [comment]
The latest release should fix this problem. https://github.com/shubhamjain/quick-grayscale/releases/tag/0.1.2

Although, this will only check for dark mode an app start. Meaning the icon wouldn't get changed if you change the appearance while the app is still running.

**Comment by ploum** [comment]
Wonderful, thanks for the quick fix.
